### ISSUE TITLE
PS/2 to spi then spi to USB

### ISSUE THREAD

**Issue by youxiaojie** [rileymcdowell/ps2-to-usb#1]
I hope to modify this , firstly convert PS/2 to spi then spi to USB,this can be transferred by nrf24l01. Who can give me some advices?Is this teensy 2 atm32U4 in dependent? Can it used in arduino pro micro for lower price?

**Comment by rileymcdowell** [comment]
You are free to modify the code I contributed to this repo as you see fit. In fact I encourage you to fork it and improve upon it. 

* For advice, I recommend using Google heavily, that's how I learned how to do this.
* In its current state, this repo is completely dependent on on the Teensy microcontroller framework/libraries. It's certainly possible to move it to a different microcontroller, but it will require changing some of the code. If you're working on a personal project, the Teensy controllers are very reasonably priced, I would encourage you to pick one up rather than saving $10 USD and moving to a controller with inferior community support.

* If you are working on a professional/for profit project and wish to reduce cost to increase margins, I strongly recommend reviewing the licenses of the code used in this project. Some of them may not be compatible with non-open source licenses. 

Good luck with your project!
